# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# Primary region provider
provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = {
      Project     = "aws-dr-project"
      Environment = "dev"
      ManagedBy   = "terragrunt"
      Repository  = "aws-dr-project"
    }
  }
}

# Secondary region provider for DR
provider "aws" {
  alias  = "secondary"
  region = "us-west-2"

  default_tags {
    tags = {
      Project     = "aws-dr-project"
      Environment = "dev"
      ManagedBy   = "terragrunt"
      Repository  = "aws-dr-project"
      Purpose     = "disaster-recovery"
    }
  }
}
